### ISSUE TITLE
CSAPP lab 0

### ISSUE THREAD

**Issue by williammrt** [Yansongsongsong/CSAPP-Experiments#1]
Hi Yannick big old, can you also add 15213 lab 0 to this project? My only source of that is https://github.com/JonnyKong/CMU-15-213-Intro-to-Computer-Systems/tree/master/LAB0_cprogramminglab. Thanks.

**Comment by Gnosnay** [comment]
@williammrt hi i am so sorry to reply u so late. yeah let me have a look on it

**Comment by Gnosnay** [comment]
@williammrt HI, i am so sorry for that I couldn't add the lab0 to this project, because it can not be found in the official lab website.
this repo is trying to give some guys one easy-to-use env to do these labs. but now, it seems that there is no description or lab tutorial for lab0. 

so...  would you mind giving the link of lab0 web page archive?

**Comment by williammrt** [comment]
@Yansongsongsong  Thanks for reply. Just ignore the lab0.

**Comment by williammrt** [comment]
My computer is so old that it can't install dockor

**Comment by Gnosnay** [comment]
> My computer is so old that it can't install dockor

could u please give more info, maybe i could help u

**Comment by williammrt** [comment]
Thanks, my computer is around 10 years old... It uses Intel Pentium E5300, and windows7, which does not support hyper-v. I have tried to install  Docker Toolbox, but it is no longer available. Now I use VirtualBox for the labs. I just finished partials of lab1 after two months....

**Comment by Gnosnay** [comment]
> Thanks, my computer is around 10 years old... It uses Intel Pentium E5300, and windows7, which does not support hyper-v. I have tried to install Docker Toolbox, but it is no longer available. Now I use VirtualBox for the labs. I just finished partials of lab1 after two months....

yeah.. how do you think install one linux system instead of win of virtual box? 
I recommend this OS: https://www.deepin.org/en/ 
it is very pretty and easy-to-use for computer that is not so good .
